### ISSUE TITLE
Excluding Specific Users from Flood Control

### ISSUE THREAD

**Issue by JmactheAttack** [Natenom/antiflood-for-mumo#1]
I noticed that you included the line `('excluded_for_antiflood', str, 'excludedantiflood')` in your scripts configuration settings, but it doesn't look like it is actually implemented anywhere in the script. Am I reading this correctly? I have several client-side bots that run and so I'm really looking at using this module to protect them from abuse and also to screen them from getting kicked because in the case of one of them, it's bridging a Jabber chat room that can be quite active.

**Comment by Natenom** [comment]
I think that is something I wanted to start and it was committed by accident ... just ignore it :)

**Comment by Natenom** [comment]
Implemented, and works for me; see  f1e4f4a.
